package com.droid.bss.infrastructure.streams.events;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * Fraud alert generated by Kafka Streams
 */
public class FraudAlert {
    private UUID customerId;
    private String alertType;
    private String severity; // LOW, MEDIUM, HIGH, CRITICAL
    private BigDecimal amount;
    private BigDecimal expectedAmount;
    private Double ratio;
    private Long count;
    private Instant windowStart;
    private Instant windowEnd;
    private String description;

    // Getters and setters
    public UUID getCustomerId() { return customerId; }
    public void setCustomerId(UUID customerId) { this.customerId = customerId; }
    public String getAlertType() { return alertType; }
    public void setAlertType(String alertType) { this.alertType = alertType; }
    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }
    public BigDecimal getAmount() { return amount; }
    public void setAmount(BigDecimal amount) { this.amount = amount; }
    public BigDecimal getExpectedAmount() { return expectedAmount; }
    public void setExpectedAmount(BigDecimal expectedAmount) { this.expectedAmount = expectedAmount; }
    public Double getRatio() { return ratio; }
    public void setRatio(Double ratio) { this.ratio = ratio; }
    public Long getCount() { return count; }
    public void setCount(Long count) { this.count = count; }
    public Instant getWindowStart() { return windowStart; }
    public void setWindowStart(Instant windowStart) { this.windowStart = windowStart; }
    public Instant getWindowEnd() { return windowEnd; }
    public void setWindowEnd(Instant windowEnd) { this.windowEnd = windowEnd; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    // Builder
    public static class Builder {
        private FraudAlert alert = new FraudAlert();

        public Builder customerId(UUID customerId) {
            alert.customerId = customerId;
            return this;
        }

        public Builder alertType(String alertType) {
            alert.alertType = alertType;
            return this;
        }

        public Builder severity(String severity) {
            alert.severity = severity;
            return this;
        }

        public Builder amount(BigDecimal amount) {
            alert.amount = amount;
            return this;
        }

        public Builder expectedAmount(BigDecimal expectedAmount) {
            alert.expectedAmount = expectedAmount;
            return this;
        }

        public Builder ratio(Double ratio) {
            alert.ratio = ratio;
            return this;
        }

        public Builder count(Long count) {
            alert.count = count;
            return this;
        }

        public Builder windowStart(Instant windowStart) {
            alert.windowStart = windowStart;
            return this;
        }

        public Builder windowEnd(Instant windowEnd) {
            alert.windowEnd = windowEnd;
            return this;
        }

        public Builder description(String description) {
            alert.description = description;
            return this;
        }

        public FraudAlert build() {
            return alert;
        }
    }

    public static Builder builder() {
        return new Builder();
    }
}
